Updating to repo aws_CF_LAMP_Template.yaml

diff --git a/aws_CF_LAMP_Template.yaml b/aws_CF_LAMP_Template.yaml
--- a/aws_CF_LAMP_Template.yaml
+++ b/aws_CF_LAMP_Template.yaml
@@ -47,6 +47,13 @@ Parameters:
     Type: CommaDelimitedList
     Default: 10.0.101.0/24,10.0.102.0/24,10.0.103.0/24
 
+  StackNameParam:
+    Type: String
+    Default: lamp-stack
+
+  AWSRegionNameParam:
+    Type: String
+    Default: eu-west-2
 Resources:
 
   VPC:
@@ -360,7 +367,6 @@ Resources:
           CidrIp: 0.0.0.0/0
 
 
-
   Ec2SecurityGroup:
     Type: AWS::EC2::SecurityGroup
     Properties:
@@ -389,7 +395,7 @@ Resources:
   TargetGroup:
     Type: AWS::ElasticLoadBalancingV2::TargetGroup
     Properties:
-      Name: WebServer-tg
+      Name: !Sub "${AWS::StackName}-tg"
       VpcId: !Ref VPC
       Port: 80
       Protocol: HTTP
@@ -397,9 +403,9 @@ Resources:
       HealthCheckProtocol: HTTP
       Matcher:
         HttpCode: 200-399
-      Targets:
-        - Id: !Ref LampInstance
-          Port: 80
+      # Targets:
+      #   - Id: !Ref LampInstance
+      #     Port: 80
 
 
   MyListener:
@@ -431,11 +437,63 @@ Resources:
   #         ToPort: 443
   #         CidrIp: 0.0.0.0/0
 
-  LampInstance:
-    Type: AWS::EC2::Instance
-    CreationPolicy:
-      ResourceSignal:
-        Timeout: PT30M
+  LampLaunchTemplate:
+    Type: AWS::EC2::LaunchTemplate
+    Properties:
+      LaunchTemplateName: lamp-stack-ec2-LaunchTemplate
+      LaunchTemplateData:
+        ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
+        # ImageId: ami-07a5595e036e5def1
+        InstanceType: !Ref InstanceType
+        KeyName: !Ref KeyName
+        IamInstanceProfile:
+          Name: !Ref EC2InstanceProfile
+        Monitoring:
+          Enabled: true
+        SecurityGroupIds:
+          - !Ref Ec2SecurityGroup
+
+        TagSpecifications:
+          - ResourceType: instance
+            Tags:
+              - Key: Name
+                Value: !Sub "${AWS::StackName}_private-subnet-EC2"
+
+
+
+        UserData: !Base64 |
+          #!/bin/bash -xe
+          yum clean all
+          yum update -y
+
+          
+          dnf install -y aws-cfn-bootstrap
+
+          /opt/aws/bin/cfn-init \
+            --stack lamp-stack \
+            --resource LampAutoScalingGroup \
+            --region eu-west-2 \
+            --configsets default
+
+            # --stack ${AWS::StackName} \
+            # --stack ${StackNameParam} \
+            # --region ${AWS::Region} \
+            #--region ${AWSRegionNameParam} \
+
+
+          INIT_EXIT_CODE=$?
+
+          /opt/aws/bin/cfn-signal \
+            --exit-code $INIT_EXIT_CODE \
+            --stack lamp-stack \
+            --resource LampAutoScalingGroup \
+            --region eu-west-2
+          
+          exit $INIT_EXIT_CODE
+
+  LampAutoScalingGroup:
+    Type: 'AWS::AutoScaling::AutoScalingGroup'
+    
     Metadata:
       AWS::CloudFormation::Init:
         configSets:
@@ -446,7 +504,7 @@ Resources:
         install:
           packages:
             yum:
-              httpd: []
+              # httpd: []
               wget: []
               # php: []
               # php-fpm: []
@@ -455,10 +513,10 @@ Resources:
               # php-devel: []
               # php-gd: []
               # php-json: []
-              mariadb105-server: []
+              # mariadb105-server: []
               openssl: []
-              mod_ssl: []
-              stress: []
+              # mod_ssl: []
+              # stress: []
 
         configure:
           commands:
@@ -639,10 +697,10 @@ Resources:
               content: !Sub |
                 [cfn-auto-reloader-hook]
                 triggers=post.update
-                path=Resources.LampInstance.Metadata.AWS::CloudFormation::Init
+                path=Resources.LampAutoScalingGroup.Metadata.AWS::CloudFormation::Init
                 action=/opt/aws/bin/cfn-init \
                   --stack ${AWS::StackName} \
-                  --resource LampInstance \
+                  --resource LampAutoScalingGroup \
                   --region ${AWS::Region} \
                   --configsets default
                 runas=root
@@ -653,54 +711,319 @@ Resources:
                 enabled: true
                 ensureRunning: true
 
+
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT30M
+        Count: 1
+      AutoScalingCreationPolicy:
+        MinSuccessfulInstancesPercent: 0
+
+    UpdatePolicy:
+      AutoScalingRollingUpdate:
+        MinInstancesInService: 1
+        MaxBatchSize: 3
+        PauseTime: PT30M
+        WaitOnResourceSignals: true
+
     Properties:
-      InstanceType: !Ref InstanceType
-      KeyName: !Ref KeyName
-      SubnetId: !Ref PrivateSubnet1
-      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
-      SecurityGroupIds:
-        # - !Ref LampSecurityGroup
-        - !Ref PrivateInstanceSG
-        - !Ref Ec2SecurityGroup
-      Tags:
-        - Key: Name
-          Value: !Sub "${AWS::StackName}_private-subnet-EC2"
+      AutoScalingGroupName: LampAutoScalingGroup
+      DesiredCapacity: 1
+      MaxSize: 3
+      MinSize: 1
+      VPCZoneIdentifier:
+        - !Ref PrivateSubnet1
+        - !Ref PrivateSubnet2
+        - !Ref PrivateSubnet3
+      LaunchTemplate:
+        LaunchTemplateId: !Ref LampLaunchTemplate
+        Version: !GetAtt LampLaunchTemplate.LatestVersionNumber
+      TargetGroupARNs:
+        - !Ref TargetGroup
+      HealthCheckType: ELB
+      HealthCheckGracePeriod: 300
 
-      UserData:
-        Fn::Base64: !Sub |
-          #!/bin/bash -xe
-          yum clean all
-          yum update -y
+  TargetTrackingScalingPolicy:
+    Type: AWS::AutoScaling::ScalingPolicy
+    Properties:
+      AutoScalingGroupName: !Ref LampAutoScalingGroup
+      PolicyType: TargetTrackingScaling
+      TargetTrackingConfiguration:
+        PredefinedMetricSpecification:
+          PredefinedMetricType: ASGAverageCPUUtilization
+        TargetValue: 50.0
+        DisableScaleIn: false
+  # LampInstance:
+  #   Type: AWS::EC2::Instance
+  #   CreationPolicy:
+  #     ResourceSignal:
+  #       Timeout: PT30M
+  #   Metadata:
+  #     AWS::CloudFormation::Init:
+  #       configSets:
+  #         default:
+  #           - install
+  #           - configure
+  #           - cfn-hup
+  #       install:
+  #         packages:
+  #           yum:
+  #             httpd: []
+  #             wget: []
+  #             # php: []
+  #             # php-fpm: []
+  #             # php-mysqlnd: []
+  #             # php-mysqli: []
+  #             # php-devel: []
+  #             # php-gd: []
+  #             # php-json: []
+  #             mariadb105-server: []
+  #             openssl: []
+  #             mod_ssl: []
+  #             stress: []
+
+  #       configure:
+  #         commands:
+  #           01_permissions:
+  #             command: |
+                
+  #               #TODO check why the packages are not installed via config:packages:dnf
+  #               #dnf isnt supported by packages, though not sure why aws wouldn't throw an error, 
+  #               # but very well throws errors for any issues with yum install.
+  #               # yum install is flaky given the repo isnt accessible though user data runs before the install.
+  #               # yum update has been included in the user data.
+  #               dnf upgrade -y
+  #               dnf install -y httpd wget php php-fpm php-mysqlnd php-mysqli php-json php-devel php-gd mariadb105-server openssl mod_ssl stress
+                  
+  #               WEB_ROOT="/var/www/html"
+  #               INDEX_FILE="$WEB_ROOT/index.php"
+
+  #               # Ensure web root exists
+  #               mkdir -p "$WEB_ROOT"
+
+  #               # Create index.php only if it does not exist
+  #               if [ ! -f "$INDEX_FILE" ]; then
+  #                 echo '<?php phpinfo(); ?>' > "$INDEX_FILE"
+  #               fi
+
+  #               # Fix ownership and permissions
+  #               chown apache:apache "$INDEX_FILE"
+  #               chmod 644 "$INDEX_FILE"
+                
+  #               usermod -a -G apache ec2-user || true
+  #               chown -R apache:apache /var/www
+  #               find /var/www -type d -exec chmod 755 {} \;
+  #               find /var/www -type f -exec chmod 644 {} \;
+
+  #           02_start_services:
+  #             command: |
+  #               systemctl enable httpd mariadb
+  #               systemctl start mariadb
+  #               until mysqladmin ping --silent; do sleep 2; done
+
+  #           03_secure_mariadb:
+  #             command: !Sub |
+  #               #!/bin/bash
+  #               set -e
+
+  #               # Wait for MariaDB
+  #               until mysqladmin ping --silent; do
+  #                 sleep 2
+  #               done
+
+  #               # Determine how to connect as root
+  #               if mysql -u root -e "SELECT 1" >/dev/null 2>&1; then
+  #                 MYSQL="mysql -u root"
+  #               elif mysql -u root -p"${DBRootPassword}" -e "SELECT 1" >/dev/null 2>&1; then
+  #                 MYSQL="mysql -u root -p${DBRootPassword}"
+  #               else
+  #                 echo "ERROR: Unable to authenticate to MariaDB as root"
+  #                 exit 1
+  #               fi
+
+  #               # Check if password already matches (idempotent)
+  #               PASSWORD_OK=$($MYSQL -Nse "
+  #                 SELECT COUNT(*) FROM mysql.user
+  #                 WHERE User='root'
+  #                   AND Host='localhost'
+  #                   AND authentication_string = PASSWORD('${DBRootPassword}');
+  #               ")
+
+  #               if [ "$PASSWORD_OK" -eq 0 ]; then
+  #                 echo "Setting MariaDB root password"
+  #                 $MYSQL -e "
+  #                   ALTER USER 'root'@'localhost' IDENTIFIED BY '${DBRootPassword}';
+  #                   FLUSH PRIVILEGES;
+  #                 "
+  #               else
+  #                 echo "MariaDB root password already set — skipping"
+  #               fi
+
+                
+  #               #mysql -e "ALTER USER IF EXISTS 'root'@'localhost' IDENTIFIED BY '${DBRootPassword}'; FLUSH PRIVILEGES;"
+  #               mysql -u root --password=${DBRootPassword} -e "
+  #                 DELETE FROM mysql.user WHERE User='';
+  #                 DROP DATABASE IF EXISTS test;
+  #                 FLUSH PRIVILEGES;
+  #               "
+
+  #           04_create_wordpress_db:
+  #             command: !Sub |
+  #               mysql -u root --password=${DBRootPassword} -e "
+  #                 CREATE DATABASE IF NOT EXISTS ${WordPressDBName};
+  #                 CREATE USER IF NOT EXISTS '${WordPressDBUser}'@'localhost'
+  #                   IDENTIFIED BY '${WordPressDBPassword}';
+  #                 GRANT ALL PRIVILEGES ON ${WordPressDBName}.* TO '${WordPressDBUser}'@'localhost';
+  #                 FLUSH PRIVILEGES;
+  #               "
+
+  #           05_install_wordpress:
+  #             command: |
+  #               cd /tmp
+  #               if [ ! -d /var/www/html/wp-admin ]; then
+  #                 wget https://wordpress.org/latest.tar.gz
+  #                 tar -xzf latest.tar.gz
+  #                 cp -r wordpress/* /var/www/html/
+  #               fi
+
+  #           06_configure_wp:
+  #             command: !Sub |
+  #               cd /var/www/html
+  #               if [ ! -f wp-config.php ]; then
+  #                 cp wp-config-sample.php wp-config.php
+  #                 sed -i "s/database_name_here/${WordPressDBName}/" wp-config.php
+  #                 sed -i "s/username_here/${WordPressDBUser}/" wp-config.php
+  #                 sed -i "s/password_here/${WordPressDBPassword}/" wp-config.php
+
+  #                 curl -s https://api.wordpress.org/secret-key/1.1/salt/ >> wp-config.php
+  #               fi
+
+  #           07_fix_wp_permissions:
+  #             command: |
+  #               chown -R apache:apache /var/www/html
+  #               find /var/www/html -type d -exec chmod 755 {} \;
+  #               find /var/www/html -type f -exec chmod 644 {} \;
+
+  #           08_generate_self_signed_cert:
+  #             command: |
+  #               CERT=/etc/pki/tls/certs/apache-selfsigned.crt
+  #               KEY=/etc/pki/tls/private/apache-selfsigned.key
+
+  #               if [ ! -f "$CERT" ] || [ ! -f "$KEY" ]; then
+
+  #                 openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
+  #                   -keyout $KEY \
+  #                   -out $CERT \
+  #                   -subj "/C=GB/ST=Scotland/L=Glasgow/O=KampliLimited/OU=IT/CN=kamplidev.com/emailAddress=kampli@gmail.com"
+  #               fi
+
+  #           09_configure_ssl:
+  #             command: |
+  #               SSL_CONF=/etc/httpd/conf.d/ssl.conf
+  #               sed -i \
+  #                 -e 's|^SSLCertificateFile .*|SSLCertificateFile /etc/pki/tls/certs/apache-selfsigned.crt|' \
+  #                 -e 's|^SSLCertificateKeyFile .*|SSLCertificateKeyFile /etc/pki/tls/private/apache-selfsigned.key|' \
+  #                 $SSL_CONF
+
+  #           10_restart_httpd:
+  #             command: |
+  #               testFileName=/var/log/$(date +'%Y%m%d%H%M%S')_touchfile.log
+  #               touch $testFileName
+  #               chmod 777 $testFileName
+
+  #               systemctl restart httpd
+
+  #         services:
+  #           systemd:
+  #             httpd:
+  #               enabled: true
+  #               ensureRunning: true
+  #             mariadb:
+  #               enabled: true
+  #               ensureRunning: true
+
+  #       cfn-hup:
+  #         files:
+  #           /etc/cfn/cfn-hup.conf:
+  #             mode: "0400"
+  #             owner: root
+  #             group: root
+  #             content: !Sub |
+  #               [main]
+  #               stack=${AWS::StackId}
+  #               region=${AWS::Region}
+  #               interval=5
+
+  #           /etc/cfn/hooks.d/cfn-auto-reloader.conf:
+  #             mode: "0400"
+  #             owner: root
+  #             group: root
+  #             content: !Sub |
+  #               [cfn-auto-reloader-hook]
+  #               triggers=post.update
+  #               path=Resources.LampInstance.Metadata.AWS::CloudFormation::Init
+  #               action=/opt/aws/bin/cfn-init \
+  #                 --stack ${AWS::StackName} \
+  #                 --resource LampInstance \
+  #                 --region ${AWS::Region} \
+  #                 --configsets default
+  #               runas=root
+
+  #         services:
+  #           systemd:
+  #             cfn-hup:
+  #               enabled: true
+  #               ensureRunning: true
+
+  #   Properties:
+  #     InstanceType: !Ref InstanceType
+  #     KeyName: !Ref KeyName
+  #     # SubnetId: !Ref PrivateSubnet1
+  #     ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
+  #     SecurityGroupIds:
+  #       # - !Ref LampSecurityGroup
+  #       - !Ref PrivateInstanceSG
+  #       - !Ref Ec2SecurityGroup
+  #     Tags:
+  #       - Key: Name
+  #         Value: !Sub "${AWS::StackName}_private-subnet-EC2"
+
+  #     UserData:
+  #       Fn::Base64: !Sub |
+  #         #!/bin/bash -xe
+  #         yum clean all
+  #         yum update -y
 
           
-          dnf install -y aws-cfn-bootstrap
+  #         dnf install -y aws-cfn-bootstrap
 
-          /opt/aws/bin/cfn-init \
-            --stack ${AWS::StackName} \
-            --resource LampInstance \
-            --region ${AWS::Region} \
-            --configsets default
+  #         /opt/aws/bin/cfn-init \
+  #           --stack ${AWS::StackName} \
+  #           --resource LampInstance \
+  #           --region ${AWS::Region} \
+  #           --configsets default
 
-          INIT_EXIT_CODE=$?
+  #         INIT_EXIT_CODE=$?
 
-          /opt/aws/bin/cfn-signal \
-            --exit-code $INIT_EXIT_CODE \
-            --stack ${AWS::StackName} \
-            --resource LampInstance \
-            --region ${AWS::Region}
+  #         /opt/aws/bin/cfn-signal \
+  #           --exit-code $INIT_EXIT_CODE \
+  #           --stack ${AWS::StackName} \
+  #           --resource LampInstance \
+  #           --region ${AWS::Region}
           
-          exit $INIT_EXIT_CODE
+  #         exit $INIT_EXIT_CODE
+
 
 Outputs:
   InstancePublicIP:
     Description: Public IP address of the LAMP EC2 instance
     # Value: !GetAtt LampInstance.PublicIp
-    Value: !GetAtt LampInstance.PrivateIp
+    Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
 
   PublicDNS:
     Description: Public DNS of the LAMP Stack EC2
     # Value: !GetAtt LampInstance.PublicDnsName
-    Value: !GetAtt LampInstance.PrivateDnsName
+    Value: !GetAtt ApplicationLoadBalancer.DNSName
 
   InstanceName:
     Description: Name of the LAMP EC2 instance
